---
- name: Test andrewrothstein.epel
  hosts: all
  tasks:
    - name: Installing andrewrothstein.epel
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Install an EPEL hosted package
      become: true
      become_user: root
      package:
        name: tor
        state: present
