---
- name: (CentOS/RedHat) install EPEL
  become: yes
  become_user: root
  when: ansible_distribution in ['CentOS','RedHat']
  package:
    name: epel-release
    state: present
  register: install_epel
  until: install_epel is success
  retries: 10
  delay: 2
